### ISSUE TITLE
is ghcid-dummy sign absolutely necessary?

### ISSUE THREAD

**Issue by zekzekus** [cloudhead/neovim-ghcid#2]
i am using your plugin and it's speed looks really promising. so thank for you effort in the first place. 

IMHO, the dummy sign you defined is very frustrating for the clean situation of the current file. even if there is no errors or warnings the sign column sits there persistently. with syntastic and neomake people usually are used to see sign column only if there is an actual sign on it.

**Comment by cloudhead** [comment]
This will be fixed. I personally prefer the sign column to always be there because I don't like things moving around everytime there's an error, but it should definitely be optional. Vim (HEAD) recently introduced an option to control the visibility of the column, `set signcolumn=yes/no`, and once that gets merged into neovim there won't be a need to do that in the plugin. For now though, I'll add a workaround.

**Comment by cloudhead** [comment]
I pushed a change with a configurable `g:ghcid_signcolumn`. It defaults to `2`, which is to only show the column when there are signs, `1` is always, `0` is never.

Note that the signs are removed on `TextChanged`, since any line insert will make them refer to the wrong line.

**Comment by zekzekus** [comment]
thanks for quick response. to make it configurable is a great solution.
